#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LayerData
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLNHANSU")]
	public partial class QLNSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBAOHIEM(BAOHIEM instance);
    partial void UpdateBAOHIEM(BAOHIEM instance);
    partial void DeleteBAOHIEM(BAOHIEM instance);
    partial void InsertCHUCVU(CHUCVU instance);
    partial void UpdateCHUCVU(CHUCVU instance);
    partial void DeleteCHUCVU(CHUCVU instance);
    partial void InsertDANTOC(DANTOC instance);
    partial void UpdateDANTOC(DANTOC instance);
    partial void DeleteDANTOC(DANTOC instance);
    partial void InsertLOAIBAOHIEM(LOAIBAOHIEM instance);
    partial void UpdateLOAIBAOHIEM(LOAIBAOHIEM instance);
    partial void DeleteLOAIBAOHIEM(LOAIBAOHIEM instance);
    partial void InsertLYLICH(LYLICH instance);
    partial void UpdateLYLICH(LYLICH instance);
    partial void DeleteLYLICH(LYLICH instance);
    partial void InsertNGOAINGU(NGOAINGU instance);
    partial void UpdateNGOAINGU(NGOAINGU instance);
    partial void DeleteNGOAINGU(NGOAINGU instance);
    partial void InsertNHANVIIEN(NHANVIIEN instance);
    partial void UpdateNHANVIIEN(NHANVIIEN instance);
    partial void DeleteNHANVIIEN(NHANVIIEN instance);
    partial void InsertPHONGBAN(PHONGBAN instance);
    partial void UpdatePHONGBAN(PHONGBAN instance);
    partial void DeletePHONGBAN(PHONGBAN instance);
    partial void InsertQUOCTICH(QUOCTICH instance);
    partial void UpdateQUOCTICH(QUOCTICH instance);
    partial void DeleteQUOCTICH(QUOCTICH instance);
    partial void InsertTHANNHAN(THANNHAN instance);
    partial void UpdateTHANNHAN(THANNHAN instance);
    partial void DeleteTHANNHAN(THANNHAN instance);
    partial void InsertTINHOC(TINHOC instance);
    partial void UpdateTINHOC(TINHOC instance);
    partial void DeleteTINHOC(TINHOC instance);
    partial void InsertTONGIAO(TONGIAO instance);
    partial void UpdateTONGIAO(TONGIAO instance);
    partial void DeleteTONGIAO(TONGIAO instance);
    partial void InsertTRINHDOCHUYENMON(TRINHDOCHUYENMON instance);
    partial void UpdateTRINHDOCHUYENMON(TRINHDOCHUYENMON instance);
    partial void DeleteTRINHDOCHUYENMON(TRINHDOCHUYENMON instance);
    partial void InsertUNGVIEN(UNGVIEN instance);
    partial void UpdateUNGVIEN(UNGVIEN instance);
    partial void DeleteUNGVIEN(UNGVIEN instance);
    #endregion
		
		public QLNSDataContext() : 
				base(global::LayerData.Properties.Settings.Default.QLNHANSUConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLNSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BAOHIEM> BAOHIEMs
		{
			get
			{
				return this.GetTable<BAOHIEM>();
			}
		}
		
		public System.Data.Linq.Table<CHUCVU> CHUCVUs
		{
			get
			{
				return this.GetTable<CHUCVU>();
			}
		}
		
		public System.Data.Linq.Table<DANTOC> DANTOCs
		{
			get
			{
				return this.GetTable<DANTOC>();
			}
		}
		
		public System.Data.Linq.Table<LOAIBAOHIEM> LOAIBAOHIEMs
		{
			get
			{
				return this.GetTable<LOAIBAOHIEM>();
			}
		}
		
		public System.Data.Linq.Table<LYLICH> LYLICHes
		{
			get
			{
				return this.GetTable<LYLICH>();
			}
		}
		
		public System.Data.Linq.Table<NGOAINGU> NGOAINGUs
		{
			get
			{
				return this.GetTable<NGOAINGU>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIIEN> NHANVIIENs
		{
			get
			{
				return this.GetTable<NHANVIIEN>();
			}
		}
		
		public System.Data.Linq.Table<PHONGBAN> PHONGBANs
		{
			get
			{
				return this.GetTable<PHONGBAN>();
			}
		}
		
		public System.Data.Linq.Table<QUOCTICH> QUOCTICHes
		{
			get
			{
				return this.GetTable<QUOCTICH>();
			}
		}
		
		public System.Data.Linq.Table<THANNHAN> THANNHANs
		{
			get
			{
				return this.GetTable<THANNHAN>();
			}
		}
		
		public System.Data.Linq.Table<TINHOC> TINHOCs
		{
			get
			{
				return this.GetTable<TINHOC>();
			}
		}
		
		public System.Data.Linq.Table<TONGIAO> TONGIAOs
		{
			get
			{
				return this.GetTable<TONGIAO>();
			}
		}
		
		public System.Data.Linq.Table<TRINHDOCHUYENMON> TRINHDOCHUYENMONs
		{
			get
			{
				return this.GetTable<TRINHDOCHUYENMON>();
			}
		}
		
		public System.Data.Linq.Table<UNGVIEN> UNGVIENs
		{
			get
			{
				return this.GetTable<UNGVIEN>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BAOHIEM")]
	public partial class BAOHIEM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_BAOHIEM;
		
		private string _ID_LOAIBH;
		
		private string _ID_NHANVIEN;
		
		private string _MASOBAOHIEM;
		
		private System.Nullable<System.DateTime> _NGAYCAPBHXH;
		
		private System.Nullable<System.DateTime> _NGAYCAPBHYT;
		
		private string _BENHVIEN;
		
		private EntityRef<LOAIBAOHIEM> _LOAIBAOHIEM;
		
		private EntityRef<NHANVIIEN> _NHANVIIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_BAOHIEMChanging(string value);
    partial void OnID_BAOHIEMChanged();
    partial void OnID_LOAIBHChanging(string value);
    partial void OnID_LOAIBHChanged();
    partial void OnID_NHANVIENChanging(string value);
    partial void OnID_NHANVIENChanged();
    partial void OnMASOBAOHIEMChanging(string value);
    partial void OnMASOBAOHIEMChanged();
    partial void OnNGAYCAPBHXHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYCAPBHXHChanged();
    partial void OnNGAYCAPBHYTChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYCAPBHYTChanged();
    partial void OnBENHVIENChanging(string value);
    partial void OnBENHVIENChanged();
    #endregion
		
		public BAOHIEM()
		{
			this._LOAIBAOHIEM = default(EntityRef<LOAIBAOHIEM>);
			this._NHANVIIEN = default(EntityRef<NHANVIIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_BAOHIEM", DbType="Char(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_BAOHIEM
		{
			get
			{
				return this._ID_BAOHIEM;
			}
			set
			{
				if ((this._ID_BAOHIEM != value))
				{
					this.OnID_BAOHIEMChanging(value);
					this.SendPropertyChanging();
					this._ID_BAOHIEM = value;
					this.SendPropertyChanged("ID_BAOHIEM");
					this.OnID_BAOHIEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOAIBH", DbType="Char(15)")]
		public string ID_LOAIBH
		{
			get
			{
				return this._ID_LOAIBH;
			}
			set
			{
				if ((this._ID_LOAIBH != value))
				{
					if (this._LOAIBAOHIEM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_LOAIBHChanging(value);
					this.SendPropertyChanging();
					this._ID_LOAIBH = value;
					this.SendPropertyChanged("ID_LOAIBH");
					this.OnID_LOAIBHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NHANVIEN", DbType="Char(15)")]
		public string ID_NHANVIEN
		{
			get
			{
				return this._ID_NHANVIEN;
			}
			set
			{
				if ((this._ID_NHANVIEN != value))
				{
					if (this._NHANVIIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_NHANVIENChanging(value);
					this.SendPropertyChanging();
					this._ID_NHANVIEN = value;
					this.SendPropertyChanged("ID_NHANVIEN");
					this.OnID_NHANVIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MASOBAOHIEM", DbType="VarChar(20)")]
		public string MASOBAOHIEM
		{
			get
			{
				return this._MASOBAOHIEM;
			}
			set
			{
				if ((this._MASOBAOHIEM != value))
				{
					this.OnMASOBAOHIEMChanging(value);
					this.SendPropertyChanging();
					this._MASOBAOHIEM = value;
					this.SendPropertyChanged("MASOBAOHIEM");
					this.OnMASOBAOHIEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYCAPBHXH", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYCAPBHXH
		{
			get
			{
				return this._NGAYCAPBHXH;
			}
			set
			{
				if ((this._NGAYCAPBHXH != value))
				{
					this.OnNGAYCAPBHXHChanging(value);
					this.SendPropertyChanging();
					this._NGAYCAPBHXH = value;
					this.SendPropertyChanged("NGAYCAPBHXH");
					this.OnNGAYCAPBHXHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYCAPBHYT", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYCAPBHYT
		{
			get
			{
				return this._NGAYCAPBHYT;
			}
			set
			{
				if ((this._NGAYCAPBHYT != value))
				{
					this.OnNGAYCAPBHYTChanging(value);
					this.SendPropertyChanging();
					this._NGAYCAPBHYT = value;
					this.SendPropertyChanged("NGAYCAPBHYT");
					this.OnNGAYCAPBHYTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BENHVIEN", DbType="NVarChar(50)")]
		public string BENHVIEN
		{
			get
			{
				return this._BENHVIEN;
			}
			set
			{
				if ((this._BENHVIEN != value))
				{
					this.OnBENHVIENChanging(value);
					this.SendPropertyChanging();
					this._BENHVIEN = value;
					this.SendPropertyChanged("BENHVIEN");
					this.OnBENHVIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIBAOHIEM_BAOHIEM", Storage="_LOAIBAOHIEM", ThisKey="ID_LOAIBH", OtherKey="ID_LOAIBH", IsForeignKey=true)]
		public LOAIBAOHIEM LOAIBAOHIEM
		{
			get
			{
				return this._LOAIBAOHIEM.Entity;
			}
			set
			{
				LOAIBAOHIEM previousValue = this._LOAIBAOHIEM.Entity;
				if (((previousValue != value) 
							|| (this._LOAIBAOHIEM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAIBAOHIEM.Entity = null;
						previousValue.BAOHIEMs.Remove(this);
					}
					this._LOAIBAOHIEM.Entity = value;
					if ((value != null))
					{
						value.BAOHIEMs.Add(this);
						this._ID_LOAIBH = value.ID_LOAIBH;
					}
					else
					{
						this._ID_LOAIBH = default(string);
					}
					this.SendPropertyChanged("LOAIBAOHIEM");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIIEN_BAOHIEM", Storage="_NHANVIIEN", ThisKey="ID_NHANVIEN", OtherKey="ID_NHANVIEN", IsForeignKey=true)]
		public NHANVIIEN NHANVIIEN
		{
			get
			{
				return this._NHANVIIEN.Entity;
			}
			set
			{
				NHANVIIEN previousValue = this._NHANVIIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIIEN.Entity = null;
						previousValue.BAOHIEMs.Remove(this);
					}
					this._NHANVIIEN.Entity = value;
					if ((value != null))
					{
						value.BAOHIEMs.Add(this);
						this._ID_NHANVIEN = value.ID_NHANVIEN;
					}
					else
					{
						this._ID_NHANVIEN = default(string);
					}
					this.SendPropertyChanged("NHANVIIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHUCVU")]
	public partial class CHUCVU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_CHUCVU;
		
		private string _CHUC_VU;
		
		private EntitySet<NHANVIIEN> _NHANVIIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CHUCVUChanging(string value);
    partial void OnID_CHUCVUChanged();
    partial void OnCHUC_VUChanging(string value);
    partial void OnCHUC_VUChanged();
    #endregion
		
		public CHUCVU()
		{
			this._NHANVIIENs = new EntitySet<NHANVIIEN>(new Action<NHANVIIEN>(this.attach_NHANVIIENs), new Action<NHANVIIEN>(this.detach_NHANVIIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CHUCVU", DbType="Char(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_CHUCVU
		{
			get
			{
				return this._ID_CHUCVU;
			}
			set
			{
				if ((this._ID_CHUCVU != value))
				{
					this.OnID_CHUCVUChanging(value);
					this.SendPropertyChanging();
					this._ID_CHUCVU = value;
					this.SendPropertyChanged("ID_CHUCVU");
					this.OnID_CHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHUC_VU", DbType="NVarChar(50)")]
		public string CHUC_VU
		{
			get
			{
				return this._CHUC_VU;
			}
			set
			{
				if ((this._CHUC_VU != value))
				{
					this.OnCHUC_VUChanging(value);
					this.SendPropertyChanging();
					this._CHUC_VU = value;
					this.SendPropertyChanged("CHUC_VU");
					this.OnCHUC_VUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUCVU_NHANVIIEN", Storage="_NHANVIIENs", ThisKey="ID_CHUCVU", OtherKey="ID_CHUCVU")]
		public EntitySet<NHANVIIEN> NHANVIIENs
		{
			get
			{
				return this._NHANVIIENs;
			}
			set
			{
				this._NHANVIIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NHANVIIENs(NHANVIIEN entity)
		{
			this.SendPropertyChanging();
			entity.CHUCVU = this;
		}
		
		private void detach_NHANVIIENs(NHANVIIEN entity)
		{
			this.SendPropertyChanging();
			entity.CHUCVU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DANTOC")]
	public partial class DANTOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_DANTOC;
		
		private string _DAN_TOC;
		
		private EntitySet<LYLICH> _LYLICHes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_DANTOCChanging(string value);
    partial void OnID_DANTOCChanged();
    partial void OnDAN_TOCChanging(string value);
    partial void OnDAN_TOCChanged();
    #endregion
		
		public DANTOC()
		{
			this._LYLICHes = new EntitySet<LYLICH>(new Action<LYLICH>(this.attach_LYLICHes), new Action<LYLICH>(this.detach_LYLICHes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DANTOC", DbType="Char(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_DANTOC
		{
			get
			{
				return this._ID_DANTOC;
			}
			set
			{
				if ((this._ID_DANTOC != value))
				{
					this.OnID_DANTOCChanging(value);
					this.SendPropertyChanging();
					this._ID_DANTOC = value;
					this.SendPropertyChanged("ID_DANTOC");
					this.OnID_DANTOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAN_TOC", DbType="NVarChar(50)")]
		public string DAN_TOC
		{
			get
			{
				return this._DAN_TOC;
			}
			set
			{
				if ((this._DAN_TOC != value))
				{
					this.OnDAN_TOCChanging(value);
					this.SendPropertyChanging();
					this._DAN_TOC = value;
					this.SendPropertyChanged("DAN_TOC");
					this.OnDAN_TOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANTOC_LYLICH", Storage="_LYLICHes", ThisKey="ID_DANTOC", OtherKey="ID_DANTOC")]
		public EntitySet<LYLICH> LYLICHes
		{
			get
			{
				return this._LYLICHes;
			}
			set
			{
				this._LYLICHes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LYLICHes(LYLICH entity)
		{
			this.SendPropertyChanging();
			entity.DANTOC = this;
		}
		
		private void detach_LYLICHes(LYLICH entity)
		{
			this.SendPropertyChanging();
			entity.DANTOC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIBAOHIEM")]
	public partial class LOAIBAOHIEM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_LOAIBH;
		
		private string _LOAIBAOHIEM1;
		
		private System.Nullable<double> _MUCDONG;
		
		private EntitySet<BAOHIEM> _BAOHIEMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_LOAIBHChanging(string value);
    partial void OnID_LOAIBHChanged();
    partial void OnLOAIBAOHIEM1Changing(string value);
    partial void OnLOAIBAOHIEM1Changed();
    partial void OnMUCDONGChanging(System.Nullable<double> value);
    partial void OnMUCDONGChanged();
    #endregion
		
		public LOAIBAOHIEM()
		{
			this._BAOHIEMs = new EntitySet<BAOHIEM>(new Action<BAOHIEM>(this.attach_BAOHIEMs), new Action<BAOHIEM>(this.detach_BAOHIEMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOAIBH", DbType="Char(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_LOAIBH
		{
			get
			{
				return this._ID_LOAIBH;
			}
			set
			{
				if ((this._ID_LOAIBH != value))
				{
					this.OnID_LOAIBHChanging(value);
					this.SendPropertyChanging();
					this._ID_LOAIBH = value;
					this.SendPropertyChanged("ID_LOAIBH");
					this.OnID_LOAIBHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="LOAIBAOHIEM", Storage="_LOAIBAOHIEM1", DbType="NVarChar(50)")]
		public string LOAIBAOHIEM1
		{
			get
			{
				return this._LOAIBAOHIEM1;
			}
			set
			{
				if ((this._LOAIBAOHIEM1 != value))
				{
					this.OnLOAIBAOHIEM1Changing(value);
					this.SendPropertyChanging();
					this._LOAIBAOHIEM1 = value;
					this.SendPropertyChanged("LOAIBAOHIEM1");
					this.OnLOAIBAOHIEM1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MUCDONG", DbType="Float")]
		public System.Nullable<double> MUCDONG
		{
			get
			{
				return this._MUCDONG;
			}
			set
			{
				if ((this._MUCDONG != value))
				{
					this.OnMUCDONGChanging(value);
					this.SendPropertyChanging();
					this._MUCDONG = value;
					this.SendPropertyChanged("MUCDONG");
					this.OnMUCDONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIBAOHIEM_BAOHIEM", Storage="_BAOHIEMs", ThisKey="ID_LOAIBH", OtherKey="ID_LOAIBH")]
		public EntitySet<BAOHIEM> BAOHIEMs
		{
			get
			{
				return this._BAOHIEMs;
			}
			set
			{
				this._BAOHIEMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BAOHIEMs(BAOHIEM entity)
		{
			this.SendPropertyChanging();
			entity.LOAIBAOHIEM = this;
		}
		
		private void detach_BAOHIEMs(BAOHIEM entity)
		{
			this.SendPropertyChanging();
			entity.LOAIBAOHIEM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LYLICH")]
	public partial class LYLICH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_LYLICH;
		
		private string _ID_NHANVIEN;
		
		private string _NOISINH;
		
		private string _TINHTRANG_HONNHAN;
		
		private string _DCTAMTRU;
		
		private string _ID_DANTOC;
		
		private string _ID_QUOCTICH;
		
		private string _ID_TONGIAO;
		
		private string _ID_NGOAINGU;
		
		private string _ID_TINHOC;
		
		private string _CMND;
		
		private System.Nullable<System.DateTime> _NGAYCAP;
		
		private string _NOICAP;
		
		private string _SUCKHOE;
		
		private System.Nullable<double> _CHIEUCAO;
		
		private System.Nullable<double> _CANNANG;
		
		private string _SOTKNGANHANG;
		
		private string _TENNGANGHANG;
		
		private string _CHINHANH;
		
		private EntityRef<DANTOC> _DANTOC;
		
		private EntityRef<NGOAINGU> _NGOAINGU;
		
		private EntityRef<NHANVIIEN> _NHANVIIEN;
		
		private EntityRef<QUOCTICH> _QUOCTICH;
		
		private EntityRef<TINHOC> _TINHOC;
		
		private EntityRef<TONGIAO> _TONGIAO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_LYLICHChanging(string value);
    partial void OnID_LYLICHChanged();
    partial void OnID_NHANVIENChanging(string value);
    partial void OnID_NHANVIENChanged();
    partial void OnNOISINHChanging(string value);
    partial void OnNOISINHChanged();
    partial void OnTINHTRANG_HONNHANChanging(string value);
    partial void OnTINHTRANG_HONNHANChanged();
    partial void OnDCTAMTRUChanging(string value);
    partial void OnDCTAMTRUChanged();
    partial void OnID_DANTOCChanging(string value);
    partial void OnID_DANTOCChanged();
    partial void OnID_QUOCTICHChanging(string value);
    partial void OnID_QUOCTICHChanged();
    partial void OnID_TONGIAOChanging(string value);
    partial void OnID_TONGIAOChanged();
    partial void OnID_NGOAINGUChanging(string value);
    partial void OnID_NGOAINGUChanged();
    partial void OnID_TINHOCChanging(string value);
    partial void OnID_TINHOCChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnNGAYCAPChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYCAPChanged();
    partial void OnNOICAPChanging(string value);
    partial void OnNOICAPChanged();
    partial void OnSUCKHOEChanging(string value);
    partial void OnSUCKHOEChanged();
    partial void OnCHIEUCAOChanging(System.Nullable<double> value);
    partial void OnCHIEUCAOChanged();
    partial void OnCANNANGChanging(System.Nullable<double> value);
    partial void OnCANNANGChanged();
    partial void OnSOTKNGANHANGChanging(string value);
    partial void OnSOTKNGANHANGChanged();
    partial void OnTENNGANGHANGChanging(string value);
    partial void OnTENNGANGHANGChanged();
    partial void OnCHINHANHChanging(string value);
    partial void OnCHINHANHChanged();
    #endregion
		
		public LYLICH()
		{
			this._DANTOC = default(EntityRef<DANTOC>);
			this._NGOAINGU = default(EntityRef<NGOAINGU>);
			this._NHANVIIEN = default(EntityRef<NHANVIIEN>);
			this._QUOCTICH = default(EntityRef<QUOCTICH>);
			this._TINHOC = default(EntityRef<TINHOC>);
			this._TONGIAO = default(EntityRef<TONGIAO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LYLICH", DbType="Char(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_LYLICH
		{
			get
			{
				return this._ID_LYLICH;
			}
			set
			{
				if ((this._ID_LYLICH != value))
				{
					this.OnID_LYLICHChanging(value);
					this.SendPropertyChanging();
					this._ID_LYLICH = value;
					this.SendPropertyChanged("ID_LYLICH");
					this.OnID_LYLICHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NHANVIEN", DbType="Char(15)")]
		public string ID_NHANVIEN
		{
			get
			{
				return this._ID_NHANVIEN;
			}
			set
			{
				if ((this._ID_NHANVIEN != value))
				{
					if (this._NHANVIIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_NHANVIENChanging(value);
					this.SendPropertyChanging();
					this._ID_NHANVIEN = value;
					this.SendPropertyChanged("ID_NHANVIEN");
					this.OnID_NHANVIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOISINH", DbType="NVarChar(50)")]
		public string NOISINH
		{
			get
			{
				return this._NOISINH;
			}
			set
			{
				if ((this._NOISINH != value))
				{
					this.OnNOISINHChanging(value);
					this.SendPropertyChanging();
					this._NOISINH = value;
					this.SendPropertyChanged("NOISINH");
					this.OnNOISINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINHTRANG_HONNHAN", DbType="NVarChar(50)")]
		public string TINHTRANG_HONNHAN
		{
			get
			{
				return this._TINHTRANG_HONNHAN;
			}
			set
			{
				if ((this._TINHTRANG_HONNHAN != value))
				{
					this.OnTINHTRANG_HONNHANChanging(value);
					this.SendPropertyChanging();
					this._TINHTRANG_HONNHAN = value;
					this.SendPropertyChanged("TINHTRANG_HONNHAN");
					this.OnTINHTRANG_HONNHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DCTAMTRU", DbType="NVarChar(50)")]
		public string DCTAMTRU
		{
			get
			{
				return this._DCTAMTRU;
			}
			set
			{
				if ((this._DCTAMTRU != value))
				{
					this.OnDCTAMTRUChanging(value);
					this.SendPropertyChanging();
					this._DCTAMTRU = value;
					this.SendPropertyChanged("DCTAMTRU");
					this.OnDCTAMTRUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DANTOC", DbType="Char(15)")]
		public string ID_DANTOC
		{
			get
			{
				return this._ID_DANTOC;
			}
			set
			{
				if ((this._ID_DANTOC != value))
				{
					if (this._DANTOC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_DANTOCChanging(value);
					this.SendPropertyChanging();
					this._ID_DANTOC = value;
					this.SendPropertyChanged("ID_DANTOC");
					this.OnID_DANTOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_QUOCTICH", DbType="Char(15)")]
		public string ID_QUOCTICH
		{
			get
			{
				return this._ID_QUOCTICH;
			}
			set
			{
				if ((this._ID_QUOCTICH != value))
				{
					if (this._QUOCTICH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_QUOCTICHChanging(value);
					this.SendPropertyChanging();
					this._ID_QUOCTICH = value;
					this.SendPropertyChanged("ID_QUOCTICH");
					this.OnID_QUOCTICHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TONGIAO", DbType="Char(15)")]
		public string ID_TONGIAO
		{
			get
			{
				return this._ID_TONGIAO;
			}
			set
			{
				if ((this._ID_TONGIAO != value))
				{
					if (this._TONGIAO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_TONGIAOChanging(value);
					this.SendPropertyChanging();
					this._ID_TONGIAO = value;
					this.SendPropertyChanged("ID_TONGIAO");
					this.OnID_TONGIAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NGOAINGU", DbType="Char(15)")]
		public string ID_NGOAINGU
		{
			get
			{
				return this._ID_NGOAINGU;
			}
			set
			{
				if ((this._ID_NGOAINGU != value))
				{
					if (this._NGOAINGU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_NGOAINGUChanging(value);
					this.SendPropertyChanging();
					this._ID_NGOAINGU = value;
					this.SendPropertyChanged("ID_NGOAINGU");
					this.OnID_NGOAINGUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TINHOC", DbType="Char(15)")]
		public string ID_TINHOC
		{
			get
			{
				return this._ID_TINHOC;
			}
			set
			{
				if ((this._ID_TINHOC != value))
				{
					if (this._TINHOC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_TINHOCChanging(value);
					this.SendPropertyChanging();
					this._ID_TINHOC = value;
					this.SendPropertyChanged("ID_TINHOC");
					this.OnID_TINHOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="VarChar(20)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYCAP", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYCAP
		{
			get
			{
				return this._NGAYCAP;
			}
			set
			{
				if ((this._NGAYCAP != value))
				{
					this.OnNGAYCAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYCAP = value;
					this.SendPropertyChanged("NGAYCAP");
					this.OnNGAYCAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOICAP", DbType="NVarChar(50)")]
		public string NOICAP
		{
			get
			{
				return this._NOICAP;
			}
			set
			{
				if ((this._NOICAP != value))
				{
					this.OnNOICAPChanging(value);
					this.SendPropertyChanging();
					this._NOICAP = value;
					this.SendPropertyChanged("NOICAP");
					this.OnNOICAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUCKHOE", DbType="NVarChar(50)")]
		public string SUCKHOE
		{
			get
			{
				return this._SUCKHOE;
			}
			set
			{
				if ((this._SUCKHOE != value))
				{
					this.OnSUCKHOEChanging(value);
					this.SendPropertyChanging();
					this._SUCKHOE = value;
					this.SendPropertyChanged("SUCKHOE");
					this.OnSUCKHOEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHIEUCAO", DbType="Float")]
		public System.Nullable<double> CHIEUCAO
		{
			get
			{
				return this._CHIEUCAO;
			}
			set
			{
				if ((this._CHIEUCAO != value))
				{
					this.OnCHIEUCAOChanging(value);
					this.SendPropertyChanging();
					this._CHIEUCAO = value;
					this.SendPropertyChanged("CHIEUCAO");
					this.OnCHIEUCAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANNANG", DbType="Float")]
		public System.Nullable<double> CANNANG
		{
			get
			{
				return this._CANNANG;
			}
			set
			{
				if ((this._CANNANG != value))
				{
					this.OnCANNANGChanging(value);
					this.SendPropertyChanging();
					this._CANNANG = value;
					this.SendPropertyChanged("CANNANG");
					this.OnCANNANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOTKNGANHANG", DbType="NChar(30)")]
		public string SOTKNGANHANG
		{
			get
			{
				return this._SOTKNGANHANG;
			}
			set
			{
				if ((this._SOTKNGANHANG != value))
				{
					this.OnSOTKNGANHANGChanging(value);
					this.SendPropertyChanging();
					this._SOTKNGANHANG = value;
					this.SendPropertyChanged("SOTKNGANHANG");
					this.OnSOTKNGANHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNGANGHANG", DbType="NVarChar(50)")]
		public string TENNGANGHANG
		{
			get
			{
				return this._TENNGANGHANG;
			}
			set
			{
				if ((this._TENNGANGHANG != value))
				{
					this.OnTENNGANGHANGChanging(value);
					this.SendPropertyChanging();
					this._TENNGANGHANG = value;
					this.SendPropertyChanged("TENNGANGHANG");
					this.OnTENNGANGHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHINHANH", DbType="NVarChar(50)")]
		public string CHINHANH
		{
			get
			{
				return this._CHINHANH;
			}
			set
			{
				if ((this._CHINHANH != value))
				{
					this.OnCHINHANHChanging(value);
					this.SendPropertyChanging();
					this._CHINHANH = value;
					this.SendPropertyChanged("CHINHANH");
					this.OnCHINHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANTOC_LYLICH", Storage="_DANTOC", ThisKey="ID_DANTOC", OtherKey="ID_DANTOC", IsForeignKey=true)]
		public DANTOC DANTOC
		{
			get
			{
				return this._DANTOC.Entity;
			}
			set
			{
				DANTOC previousValue = this._DANTOC.Entity;
				if (((previousValue != value) 
							|| (this._DANTOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DANTOC.Entity = null;
						previousValue.LYLICHes.Remove(this);
					}
					this._DANTOC.Entity = value;
					if ((value != null))
					{
						value.LYLICHes.Add(this);
						this._ID_DANTOC = value.ID_DANTOC;
					}
					else
					{
						this._ID_DANTOC = default(string);
					}
					this.SendPropertyChanged("DANTOC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGOAINGU_LYLICH", Storage="_NGOAINGU", ThisKey="ID_NGOAINGU", OtherKey="ID_NGOAINGU", IsForeignKey=true)]
		public NGOAINGU NGOAINGU
		{
			get
			{
				return this._NGOAINGU.Entity;
			}
			set
			{
				NGOAINGU previousValue = this._NGOAINGU.Entity;
				if (((previousValue != value) 
							|| (this._NGOAINGU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NGOAINGU.Entity = null;
						previousValue.LYLICHes.Remove(this);
					}
					this._NGOAINGU.Entity = value;
					if ((value != null))
					{
						value.LYLICHes.Add(this);
						this._ID_NGOAINGU = value.ID_NGOAINGU;
					}
					else
					{
						this._ID_NGOAINGU = default(string);
					}
					this.SendPropertyChanged("NGOAINGU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIIEN_LYLICH", Storage="_NHANVIIEN", ThisKey="ID_NHANVIEN", OtherKey="ID_NHANVIEN", IsForeignKey=true)]
		public NHANVIIEN NHANVIIEN
		{
			get
			{
				return this._NHANVIIEN.Entity;
			}
			set
			{
				NHANVIIEN previousValue = this._NHANVIIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIIEN.Entity = null;
						previousValue.LYLICHes.Remove(this);
					}
					this._NHANVIIEN.Entity = value;
					if ((value != null))
					{
						value.LYLICHes.Add(this);
						this._ID_NHANVIEN = value.ID_NHANVIEN;
					}
					else
					{
						this._ID_NHANVIEN = default(string);
					}
					this.SendPropertyChanged("NHANVIIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QUOCTICH_LYLICH", Storage="_QUOCTICH", ThisKey="ID_QUOCTICH", OtherKey="ID_QUOCTICH", IsForeignKey=true)]
		public QUOCTICH QUOCTICH
		{
			get
			{
				return this._QUOCTICH.Entity;
			}
			set
			{
				QUOCTICH previousValue = this._QUOCTICH.Entity;
				if (((previousValue != value) 
							|| (this._QUOCTICH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QUOCTICH.Entity = null;
						previousValue.LYLICHes.Remove(this);
					}
					this._QUOCTICH.Entity = value;
					if ((value != null))
					{
						value.LYLICHes.Add(this);
						this._ID_QUOCTICH = value.ID_QUOCTICH;
					}
					else
					{
						this._ID_QUOCTICH = default(string);
					}
					this.SendPropertyChanged("QUOCTICH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TINHOC_LYLICH", Storage="_TINHOC", ThisKey="ID_TINHOC", OtherKey="ID_TINHOC", IsForeignKey=true)]
		public TINHOC TINHOC
		{
			get
			{
				return this._TINHOC.Entity;
			}
			set
			{
				TINHOC previousValue = this._TINHOC.Entity;
				if (((previousValue != value) 
							|| (this._TINHOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TINHOC.Entity = null;
						previousValue.LYLICHes.Remove(this);
					}
					this._TINHOC.Entity = value;
					if ((value != null))
					{
						value.LYLICHes.Add(this);
						this._ID_TINHOC = value.ID_TINHOC;
					}
					else
					{
						this._ID_TINHOC = default(string);
					}
					this.SendPropertyChanged("TINHOC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TONGIAO_LYLICH", Storage="_TONGIAO", ThisKey="ID_TONGIAO", OtherKey="ID_TONGIAO", IsForeignKey=true)]
		public TONGIAO TONGIAO
		{
			get
			{
				return this._TONGIAO.Entity;
			}
			set
			{
				TONGIAO previousValue = this._TONGIAO.Entity;
				if (((previousValue != value) 
							|| (this._TONGIAO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TONGIAO.Entity = null;
						previousValue.LYLICHes.Remove(this);
					}
					this._TONGIAO.Entity = value;
					if ((value != null))
					{
						value.LYLICHes.Add(this);
						this._ID_TONGIAO = value.ID_TONGIAO;
					}
					else
					{
						this._ID_TONGIAO = default(string);
					}
					this.SendPropertyChanged("TONGIAO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NGOAINGU")]
	public partial class NGOAINGU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_NGOAINGU;
		
		private string _NGOAI_NGU;
		
		private EntitySet<LYLICH> _LYLICHes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_NGOAINGUChanging(string value);
    partial void OnID_NGOAINGUChanged();
    partial void OnNGOAI_NGUChanging(string value);
    partial void OnNGOAI_NGUChanged();
    #endregion
		
		public NGOAINGU()
		{
			this._LYLICHes = new EntitySet<LYLICH>(new Action<LYLICH>(this.attach_LYLICHes), new Action<LYLICH>(this.detach_LYLICHes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NGOAINGU", DbType="Char(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_NGOAINGU
		{
			get
			{
				return this._ID_NGOAINGU;
			}
			set
			{
				if ((this._ID_NGOAINGU != value))
				{
					this.OnID_NGOAINGUChanging(value);
					this.SendPropertyChanging();
					this._ID_NGOAINGU = value;
					this.SendPropertyChanged("ID_NGOAINGU");
					this.OnID_NGOAINGUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGOAI_NGU", DbType="NVarChar(50)")]
		public string NGOAI_NGU
		{
			get
			{
				return this._NGOAI_NGU;
			}
			set
			{
				if ((this._NGOAI_NGU != value))
				{
					this.OnNGOAI_NGUChanging(value);
					this.SendPropertyChanging();
					this._NGOAI_NGU = value;
					this.SendPropertyChanged("NGOAI_NGU");
					this.OnNGOAI_NGUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGOAINGU_LYLICH", Storage="_LYLICHes", ThisKey="ID_NGOAINGU", OtherKey="ID_NGOAINGU")]
		public EntitySet<LYLICH> LYLICHes
		{
			get
			{
				return this._LYLICHes;
			}
			set
			{
				this._LYLICHes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LYLICHes(LYLICH entity)
		{
			this.SendPropertyChanging();
			entity.NGOAINGU = this;
		}
		
		private void detach_LYLICHes(LYLICH entity)
		{
			this.SendPropertyChanging();
			entity.NGOAINGU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIIEN")]
	public partial class NHANVIIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_NHANVIEN;
		
		private string _HO_TEN;
		
		private System.Nullable<System.DateTime> _NGAY_SINH;
		
		private string _GIOI_TINH;
		
		private string _DIA_CHI;
		
		private string _DIENTHOAI;
		
		private string _EMAIL;
		
		private string _ID_PHONGBAN;
		
		private string _ID_CHUCVU;
		
		private string _ID_TDCHUYENMON;
		
		private System.Nullable<System.DateTime> _NGAYVAOLAM;
		
		private System.Nullable<int> _THOIGIANTHUVIEC;
		
		private System.Nullable<double> _LUONGCOBAN;
		
		private System.Nullable<double> _HESOLUONG;
		
		private string _SOBHXH;
		
		private string _SOBHYT;
		
		private EntitySet<BAOHIEM> _BAOHIEMs;
		
		private EntitySet<LYLICH> _LYLICHes;
		
		private EntitySet<THANNHAN> _THANNHANs;
		
		private EntityRef<CHUCVU> _CHUCVU;
		
		private EntityRef<PHONGBAN> _PHONGBAN;
		
		private EntityRef<TRINHDOCHUYENMON> _TRINHDOCHUYENMON;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_NHANVIENChanging(string value);
    partial void OnID_NHANVIENChanged();
    partial void OnHO_TENChanging(string value);
    partial void OnHO_TENChanged();
    partial void OnNGAY_SINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAY_SINHChanged();
    partial void OnGIOI_TINHChanging(string value);
    partial void OnGIOI_TINHChanged();
    partial void OnDIA_CHIChanging(string value);
    partial void OnDIA_CHIChanged();
    partial void OnDIENTHOAIChanging(string value);
    partial void OnDIENTHOAIChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnID_PHONGBANChanging(string value);
    partial void OnID_PHONGBANChanged();
    partial void OnID_CHUCVUChanging(string value);
    partial void OnID_CHUCVUChanged();
    partial void OnID_TDCHUYENMONChanging(string value);
    partial void OnID_TDCHUYENMONChanged();
    partial void OnNGAYVAOLAMChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYVAOLAMChanged();
    partial void OnTHOIGIANTHUVIECChanging(System.Nullable<int> value);
    partial void OnTHOIGIANTHUVIECChanged();
    partial void OnLUONGCOBANChanging(System.Nullable<double> value);
    partial void OnLUONGCOBANChanged();
    partial void OnHESOLUONGChanging(System.Nullable<double> value);
    partial void OnHESOLUONGChanged();
    partial void OnSOBHXHChanging(string value);
    partial void OnSOBHXHChanged();
    partial void OnSOBHYTChanging(string value);
    partial void OnSOBHYTChanged();
    #endregion
		
		public NHANVIIEN()
		{
			this._BAOHIEMs = new EntitySet<BAOHIEM>(new Action<BAOHIEM>(this.attach_BAOHIEMs), new Action<BAOHIEM>(this.detach_BAOHIEMs));
			this._LYLICHes = new EntitySet<LYLICH>(new Action<LYLICH>(this.attach_LYLICHes), new Action<LYLICH>(this.detach_LYLICHes));
			this._THANNHANs = new EntitySet<THANNHAN>(new Action<THANNHAN>(this.attach_THANNHANs), new Action<THANNHAN>(this.detach_THANNHANs));
			this._CHUCVU = default(EntityRef<CHUCVU>);
			this._PHONGBAN = default(EntityRef<PHONGBAN>);
			this._TRINHDOCHUYENMON = default(EntityRef<TRINHDOCHUYENMON>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NHANVIEN", DbType="Char(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_NHANVIEN
		{
			get
			{
				return this._ID_NHANVIEN;
			}
			set
			{
				if ((this._ID_NHANVIEN != value))
				{
					this.OnID_NHANVIENChanging(value);
					this.SendPropertyChanging();
					this._ID_NHANVIEN = value;
					this.SendPropertyChanged("ID_NHANVIEN");
					this.OnID_NHANVIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HO_TEN", DbType="NVarChar(50)")]
		public string HO_TEN
		{
			get
			{
				return this._HO_TEN;
			}
			set
			{
				if ((this._HO_TEN != value))
				{
					this.OnHO_TENChanging(value);
					this.SendPropertyChanging();
					this._HO_TEN = value;
					this.SendPropertyChanged("HO_TEN");
					this.OnHO_TENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_SINH", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAY_SINH
		{
			get
			{
				return this._NGAY_SINH;
			}
			set
			{
				if ((this._NGAY_SINH != value))
				{
					this.OnNGAY_SINHChanging(value);
					this.SendPropertyChanging();
					this._NGAY_SINH = value;
					this.SendPropertyChanged("NGAY_SINH");
					this.OnNGAY_SINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOI_TINH", DbType="NVarChar(20)")]
		public string GIOI_TINH
		{
			get
			{
				return this._GIOI_TINH;
			}
			set
			{
				if ((this._GIOI_TINH != value))
				{
					this.OnGIOI_TINHChanging(value);
					this.SendPropertyChanging();
					this._GIOI_TINH = value;
					this.SendPropertyChanged("GIOI_TINH");
					this.OnGIOI_TINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIA_CHI", DbType="NVarChar(100)")]
		public string DIA_CHI
		{
			get
			{
				return this._DIA_CHI;
			}
			set
			{
				if ((this._DIA_CHI != value))
				{
					this.OnDIA_CHIChanging(value);
					this.SendPropertyChanging();
					this._DIA_CHI = value;
					this.SendPropertyChanged("DIA_CHI");
					this.OnDIA_CHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIENTHOAI", DbType="Char(10)")]
		public string DIENTHOAI
		{
			get
			{
				return this._DIENTHOAI;
			}
			set
			{
				if ((this._DIENTHOAI != value))
				{
					this.OnDIENTHOAIChanging(value);
					this.SendPropertyChanging();
					this._DIENTHOAI = value;
					this.SendPropertyChanged("DIENTHOAI");
					this.OnDIENTHOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="Char(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PHONGBAN", DbType="Char(15)")]
		public string ID_PHONGBAN
		{
			get
			{
				return this._ID_PHONGBAN;
			}
			set
			{
				if ((this._ID_PHONGBAN != value))
				{
					if (this._PHONGBAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_PHONGBANChanging(value);
					this.SendPropertyChanging();
					this._ID_PHONGBAN = value;
					this.SendPropertyChanged("ID_PHONGBAN");
					this.OnID_PHONGBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CHUCVU", DbType="Char(15)")]
		public string ID_CHUCVU
		{
			get
			{
				return this._ID_CHUCVU;
			}
			set
			{
				if ((this._ID_CHUCVU != value))
				{
					if (this._CHUCVU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_CHUCVUChanging(value);
					this.SendPropertyChanging();
					this._ID_CHUCVU = value;
					this.SendPropertyChanged("ID_CHUCVU");
					this.OnID_CHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TDCHUYENMON", DbType="Char(15)")]
		public string ID_TDCHUYENMON
		{
			get
			{
				return this._ID_TDCHUYENMON;
			}
			set
			{
				if ((this._ID_TDCHUYENMON != value))
				{
					if (this._TRINHDOCHUYENMON.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_TDCHUYENMONChanging(value);
					this.SendPropertyChanging();
					this._ID_TDCHUYENMON = value;
					this.SendPropertyChanged("ID_TDCHUYENMON");
					this.OnID_TDCHUYENMONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYVAOLAM", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYVAOLAM
		{
			get
			{
				return this._NGAYVAOLAM;
			}
			set
			{
				if ((this._NGAYVAOLAM != value))
				{
					this.OnNGAYVAOLAMChanging(value);
					this.SendPropertyChanging();
					this._NGAYVAOLAM = value;
					this.SendPropertyChanged("NGAYVAOLAM");
					this.OnNGAYVAOLAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOIGIANTHUVIEC", DbType="Int")]
		public System.Nullable<int> THOIGIANTHUVIEC
		{
			get
			{
				return this._THOIGIANTHUVIEC;
			}
			set
			{
				if ((this._THOIGIANTHUVIEC != value))
				{
					this.OnTHOIGIANTHUVIECChanging(value);
					this.SendPropertyChanging();
					this._THOIGIANTHUVIEC = value;
					this.SendPropertyChanged("THOIGIANTHUVIEC");
					this.OnTHOIGIANTHUVIECChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUONGCOBAN", DbType="Float")]
		public System.Nullable<double> LUONGCOBAN
		{
			get
			{
				return this._LUONGCOBAN;
			}
			set
			{
				if ((this._LUONGCOBAN != value))
				{
					this.OnLUONGCOBANChanging(value);
					this.SendPropertyChanging();
					this._LUONGCOBAN = value;
					this.SendPropertyChanged("LUONGCOBAN");
					this.OnLUONGCOBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HESOLUONG", DbType="Float")]
		public System.Nullable<double> HESOLUONG
		{
			get
			{
				return this._HESOLUONG;
			}
			set
			{
				if ((this._HESOLUONG != value))
				{
					this.OnHESOLUONGChanging(value);
					this.SendPropertyChanging();
					this._HESOLUONG = value;
					this.SendPropertyChanged("HESOLUONG");
					this.OnHESOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOBHXH", DbType="Char(20)")]
		public string SOBHXH
		{
			get
			{
				return this._SOBHXH;
			}
			set
			{
				if ((this._SOBHXH != value))
				{
					this.OnSOBHXHChanging(value);
					this.SendPropertyChanging();
					this._SOBHXH = value;
					this.SendPropertyChanged("SOBHXH");
					this.OnSOBHXHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOBHYT", DbType="Char(20)")]
		public string SOBHYT
		{
			get
			{
				return this._SOBHYT;
			}
			set
			{
				if ((this._SOBHYT != value))
				{
					this.OnSOBHYTChanging(value);
					this.SendPropertyChanging();
					this._SOBHYT = value;
					this.SendPropertyChanged("SOBHYT");
					this.OnSOBHYTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIIEN_BAOHIEM", Storage="_BAOHIEMs", ThisKey="ID_NHANVIEN", OtherKey="ID_NHANVIEN")]
		public EntitySet<BAOHIEM> BAOHIEMs
		{
			get
			{
				return this._BAOHIEMs;
			}
			set
			{
				this._BAOHIEMs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIIEN_LYLICH", Storage="_LYLICHes", ThisKey="ID_NHANVIEN", OtherKey="ID_NHANVIEN")]
		public EntitySet<LYLICH> LYLICHes
		{
			get
			{
				return this._LYLICHes;
			}
			set
			{
				this._LYLICHes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIIEN_THANNHAN", Storage="_THANNHANs", ThisKey="ID_NHANVIEN", OtherKey="ID_NHANVIEN")]
		public EntitySet<THANNHAN> THANNHANs
		{
			get
			{
				return this._THANNHANs;
			}
			set
			{
				this._THANNHANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUCVU_NHANVIIEN", Storage="_CHUCVU", ThisKey="ID_CHUCVU", OtherKey="ID_CHUCVU", IsForeignKey=true)]
		public CHUCVU CHUCVU
		{
			get
			{
				return this._CHUCVU.Entity;
			}
			set
			{
				CHUCVU previousValue = this._CHUCVU.Entity;
				if (((previousValue != value) 
							|| (this._CHUCVU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHUCVU.Entity = null;
						previousValue.NHANVIIENs.Remove(this);
					}
					this._CHUCVU.Entity = value;
					if ((value != null))
					{
						value.NHANVIIENs.Add(this);
						this._ID_CHUCVU = value.ID_CHUCVU;
					}
					else
					{
						this._ID_CHUCVU = default(string);
					}
					this.SendPropertyChanged("CHUCVU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONGBAN_NHANVIIEN", Storage="_PHONGBAN", ThisKey="ID_PHONGBAN", OtherKey="ID_PHONGBAN", IsForeignKey=true)]
		public PHONGBAN PHONGBAN
		{
			get
			{
				return this._PHONGBAN.Entity;
			}
			set
			{
				PHONGBAN previousValue = this._PHONGBAN.Entity;
				if (((previousValue != value) 
							|| (this._PHONGBAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHONGBAN.Entity = null;
						previousValue.NHANVIIENs.Remove(this);
					}
					this._PHONGBAN.Entity = value;
					if ((value != null))
					{
						value.NHANVIIENs.Add(this);
						this._ID_PHONGBAN = value.ID_PHONGBAN;
					}
					else
					{
						this._ID_PHONGBAN = default(string);
					}
					this.SendPropertyChanged("PHONGBAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRINHDOCHUYENMON_NHANVIIEN", Storage="_TRINHDOCHUYENMON", ThisKey="ID_TDCHUYENMON", OtherKey="ID_TDCHUYENMON", IsForeignKey=true)]
		public TRINHDOCHUYENMON TRINHDOCHUYENMON
		{
			get
			{
				return this._TRINHDOCHUYENMON.Entity;
			}
			set
			{
				TRINHDOCHUYENMON previousValue = this._TRINHDOCHUYENMON.Entity;
				if (((previousValue != value) 
							|| (this._TRINHDOCHUYENMON.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRINHDOCHUYENMON.Entity = null;
						previousValue.NHANVIIENs.Remove(this);
					}
					this._TRINHDOCHUYENMON.Entity = value;
					if ((value != null))
					{
						value.NHANVIIENs.Add(this);
						this._ID_TDCHUYENMON = value.ID_TDCHUYENMON;
					}
					else
					{
						this._ID_TDCHUYENMON = default(string);
					}
					this.SendPropertyChanged("TRINHDOCHUYENMON");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BAOHIEMs(BAOHIEM entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIIEN = this;
		}
		
		private void detach_BAOHIEMs(BAOHIEM entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIIEN = null;
		}
		
		private void attach_LYLICHes(LYLICH entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIIEN = this;
		}
		
		private void detach_LYLICHes(LYLICH entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIIEN = null;
		}
		
		private void attach_THANNHANs(THANNHAN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIIEN = this;
		}
		
		private void detach_THANNHANs(THANNHAN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHONGBAN")]
	public partial class PHONGBAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_PHONGBAN;
		
		private string _PHONG_BAN;
		
		private EntitySet<NHANVIIEN> _NHANVIIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PHONGBANChanging(string value);
    partial void OnID_PHONGBANChanged();
    partial void OnPHONG_BANChanging(string value);
    partial void OnPHONG_BANChanged();
    #endregion
		
		public PHONGBAN()
		{
			this._NHANVIIENs = new EntitySet<NHANVIIEN>(new Action<NHANVIIEN>(this.attach_NHANVIIENs), new Action<NHANVIIEN>(this.detach_NHANVIIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PHONGBAN", DbType="Char(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_PHONGBAN
		{
			get
			{
				return this._ID_PHONGBAN;
			}
			set
			{
				if ((this._ID_PHONGBAN != value))
				{
					this.OnID_PHONGBANChanging(value);
					this.SendPropertyChanging();
					this._ID_PHONGBAN = value;
					this.SendPropertyChanged("ID_PHONGBAN");
					this.OnID_PHONGBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONG_BAN", DbType="NVarChar(50)")]
		public string PHONG_BAN
		{
			get
			{
				return this._PHONG_BAN;
			}
			set
			{
				if ((this._PHONG_BAN != value))
				{
					this.OnPHONG_BANChanging(value);
					this.SendPropertyChanging();
					this._PHONG_BAN = value;
					this.SendPropertyChanged("PHONG_BAN");
					this.OnPHONG_BANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONGBAN_NHANVIIEN", Storage="_NHANVIIENs", ThisKey="ID_PHONGBAN", OtherKey="ID_PHONGBAN")]
		public EntitySet<NHANVIIEN> NHANVIIENs
		{
			get
			{
				return this._NHANVIIENs;
			}
			set
			{
				this._NHANVIIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NHANVIIENs(NHANVIIEN entity)
		{
			this.SendPropertyChanging();
			entity.PHONGBAN = this;
		}
		
		private void detach_NHANVIIENs(NHANVIIEN entity)
		{
			this.SendPropertyChanging();
			entity.PHONGBAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QUOCTICH")]
	public partial class QUOCTICH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_QUOCTICH;
		
		private string _QUOC_TICH;
		
		private EntitySet<LYLICH> _LYLICHes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_QUOCTICHChanging(string value);
    partial void OnID_QUOCTICHChanged();
    partial void OnQUOC_TICHChanging(string value);
    partial void OnQUOC_TICHChanged();
    #endregion
		
		public QUOCTICH()
		{
			this._LYLICHes = new EntitySet<LYLICH>(new Action<LYLICH>(this.attach_LYLICHes), new Action<LYLICH>(this.detach_LYLICHes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_QUOCTICH", DbType="Char(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_QUOCTICH
		{
			get
			{
				return this._ID_QUOCTICH;
			}
			set
			{
				if ((this._ID_QUOCTICH != value))
				{
					this.OnID_QUOCTICHChanging(value);
					this.SendPropertyChanging();
					this._ID_QUOCTICH = value;
					this.SendPropertyChanged("ID_QUOCTICH");
					this.OnID_QUOCTICHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUOC_TICH", DbType="NVarChar(50)")]
		public string QUOC_TICH
		{
			get
			{
				return this._QUOC_TICH;
			}
			set
			{
				if ((this._QUOC_TICH != value))
				{
					this.OnQUOC_TICHChanging(value);
					this.SendPropertyChanging();
					this._QUOC_TICH = value;
					this.SendPropertyChanged("QUOC_TICH");
					this.OnQUOC_TICHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QUOCTICH_LYLICH", Storage="_LYLICHes", ThisKey="ID_QUOCTICH", OtherKey="ID_QUOCTICH")]
		public EntitySet<LYLICH> LYLICHes
		{
			get
			{
				return this._LYLICHes;
			}
			set
			{
				this._LYLICHes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LYLICHes(LYLICH entity)
		{
			this.SendPropertyChanging();
			entity.QUOCTICH = this;
		}
		
		private void detach_LYLICHes(LYLICH entity)
		{
			this.SendPropertyChanging();
			entity.QUOCTICH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THANNHAN")]
	public partial class THANNHAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_THANNHAN;
		
		private string _ID_NHANVIEN;
		
		private string _HOTEN_THANNHAN;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _DIACHI;
		
		private string _DIENTHOAI;
		
		private string _QUANHE;
		
		private string _GIOITINH;
		
		private EntityRef<NHANVIIEN> _NHANVIIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_THANNHANChanging(string value);
    partial void OnID_THANNHANChanged();
    partial void OnID_NHANVIENChanging(string value);
    partial void OnID_NHANVIENChanged();
    partial void OnHOTEN_THANNHANChanging(string value);
    partial void OnHOTEN_THANNHANChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnDIENTHOAIChanging(string value);
    partial void OnDIENTHOAIChanged();
    partial void OnQUANHEChanging(string value);
    partial void OnQUANHEChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    #endregion
		
		public THANNHAN()
		{
			this._NHANVIIEN = default(EntityRef<NHANVIIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_THANNHAN", DbType="Char(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_THANNHAN
		{
			get
			{
				return this._ID_THANNHAN;
			}
			set
			{
				if ((this._ID_THANNHAN != value))
				{
					this.OnID_THANNHANChanging(value);
					this.SendPropertyChanging();
					this._ID_THANNHAN = value;
					this.SendPropertyChanged("ID_THANNHAN");
					this.OnID_THANNHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NHANVIEN", DbType="Char(15)")]
		public string ID_NHANVIEN
		{
			get
			{
				return this._ID_NHANVIEN;
			}
			set
			{
				if ((this._ID_NHANVIEN != value))
				{
					if (this._NHANVIIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_NHANVIENChanging(value);
					this.SendPropertyChanging();
					this._ID_NHANVIEN = value;
					this.SendPropertyChanged("ID_NHANVIEN");
					this.OnID_NHANVIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN_THANNHAN", DbType="VarChar(50)")]
		public string HOTEN_THANNHAN
		{
			get
			{
				return this._HOTEN_THANNHAN;
			}
			set
			{
				if ((this._HOTEN_THANNHAN != value))
				{
					this.OnHOTEN_THANNHANChanging(value);
					this.SendPropertyChanging();
					this._HOTEN_THANNHAN = value;
					this.SendPropertyChanged("HOTEN_THANNHAN");
					this.OnHOTEN_THANNHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(50)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIENTHOAI", DbType="NChar(10)")]
		public string DIENTHOAI
		{
			get
			{
				return this._DIENTHOAI;
			}
			set
			{
				if ((this._DIENTHOAI != value))
				{
					this.OnDIENTHOAIChanging(value);
					this.SendPropertyChanging();
					this._DIENTHOAI = value;
					this.SendPropertyChanged("DIENTHOAI");
					this.OnDIENTHOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANHE", DbType="NVarChar(50)")]
		public string QUANHE
		{
			get
			{
				return this._QUANHE;
			}
			set
			{
				if ((this._QUANHE != value))
				{
					this.OnQUANHEChanging(value);
					this.SendPropertyChanging();
					this._QUANHE = value;
					this.SendPropertyChanged("QUANHE");
					this.OnQUANHEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(20)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIIEN_THANNHAN", Storage="_NHANVIIEN", ThisKey="ID_NHANVIEN", OtherKey="ID_NHANVIEN", IsForeignKey=true)]
		public NHANVIIEN NHANVIIEN
		{
			get
			{
				return this._NHANVIIEN.Entity;
			}
			set
			{
				NHANVIIEN previousValue = this._NHANVIIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIIEN.Entity = null;
						previousValue.THANNHANs.Remove(this);
					}
					this._NHANVIIEN.Entity = value;
					if ((value != null))
					{
						value.THANNHANs.Add(this);
						this._ID_NHANVIEN = value.ID_NHANVIEN;
					}
					else
					{
						this._ID_NHANVIEN = default(string);
					}
					this.SendPropertyChanged("NHANVIIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TINHOC")]
	public partial class TINHOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_TINHOC;
		
		private string _TIN_HOC;
		
		private EntitySet<LYLICH> _LYLICHes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_TINHOCChanging(string value);
    partial void OnID_TINHOCChanged();
    partial void OnTIN_HOCChanging(string value);
    partial void OnTIN_HOCChanged();
    #endregion
		
		public TINHOC()
		{
			this._LYLICHes = new EntitySet<LYLICH>(new Action<LYLICH>(this.attach_LYLICHes), new Action<LYLICH>(this.detach_LYLICHes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TINHOC", DbType="Char(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_TINHOC
		{
			get
			{
				return this._ID_TINHOC;
			}
			set
			{
				if ((this._ID_TINHOC != value))
				{
					this.OnID_TINHOCChanging(value);
					this.SendPropertyChanging();
					this._ID_TINHOC = value;
					this.SendPropertyChanged("ID_TINHOC");
					this.OnID_TINHOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIN_HOC", DbType="NVarChar(50)")]
		public string TIN_HOC
		{
			get
			{
				return this._TIN_HOC;
			}
			set
			{
				if ((this._TIN_HOC != value))
				{
					this.OnTIN_HOCChanging(value);
					this.SendPropertyChanging();
					this._TIN_HOC = value;
					this.SendPropertyChanged("TIN_HOC");
					this.OnTIN_HOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TINHOC_LYLICH", Storage="_LYLICHes", ThisKey="ID_TINHOC", OtherKey="ID_TINHOC")]
		public EntitySet<LYLICH> LYLICHes
		{
			get
			{
				return this._LYLICHes;
			}
			set
			{
				this._LYLICHes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LYLICHes(LYLICH entity)
		{
			this.SendPropertyChanging();
			entity.TINHOC = this;
		}
		
		private void detach_LYLICHes(LYLICH entity)
		{
			this.SendPropertyChanging();
			entity.TINHOC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TONGIAO")]
	public partial class TONGIAO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_TONGIAO;
		
		private string _TON_GIAO;
		
		private EntitySet<LYLICH> _LYLICHes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_TONGIAOChanging(string value);
    partial void OnID_TONGIAOChanged();
    partial void OnTON_GIAOChanging(string value);
    partial void OnTON_GIAOChanged();
    #endregion
		
		public TONGIAO()
		{
			this._LYLICHes = new EntitySet<LYLICH>(new Action<LYLICH>(this.attach_LYLICHes), new Action<LYLICH>(this.detach_LYLICHes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TONGIAO", DbType="Char(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_TONGIAO
		{
			get
			{
				return this._ID_TONGIAO;
			}
			set
			{
				if ((this._ID_TONGIAO != value))
				{
					this.OnID_TONGIAOChanging(value);
					this.SendPropertyChanging();
					this._ID_TONGIAO = value;
					this.SendPropertyChanged("ID_TONGIAO");
					this.OnID_TONGIAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TON_GIAO", DbType="NVarChar(50)")]
		public string TON_GIAO
		{
			get
			{
				return this._TON_GIAO;
			}
			set
			{
				if ((this._TON_GIAO != value))
				{
					this.OnTON_GIAOChanging(value);
					this.SendPropertyChanging();
					this._TON_GIAO = value;
					this.SendPropertyChanged("TON_GIAO");
					this.OnTON_GIAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TONGIAO_LYLICH", Storage="_LYLICHes", ThisKey="ID_TONGIAO", OtherKey="ID_TONGIAO")]
		public EntitySet<LYLICH> LYLICHes
		{
			get
			{
				return this._LYLICHes;
			}
			set
			{
				this._LYLICHes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LYLICHes(LYLICH entity)
		{
			this.SendPropertyChanging();
			entity.TONGIAO = this;
		}
		
		private void detach_LYLICHes(LYLICH entity)
		{
			this.SendPropertyChanging();
			entity.TONGIAO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRINHDOCHUYENMON")]
	public partial class TRINHDOCHUYENMON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_TDCHUYENMON;
		
		private string _TRINHDO_CHUYENMON;
		
		private string _BANGCAP;
		
		private string _HOCVAN_PHOTHONG;
		
		private string _NGANHDAOTAO;
		
		private string _NOIDAOTAO;
		
		private string _HINHTHUCDAOTAO;
		
		private EntitySet<NHANVIIEN> _NHANVIIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_TDCHUYENMONChanging(string value);
    partial void OnID_TDCHUYENMONChanged();
    partial void OnTRINHDO_CHUYENMONChanging(string value);
    partial void OnTRINHDO_CHUYENMONChanged();
    partial void OnBANGCAPChanging(string value);
    partial void OnBANGCAPChanged();
    partial void OnHOCVAN_PHOTHONGChanging(string value);
    partial void OnHOCVAN_PHOTHONGChanged();
    partial void OnNGANHDAOTAOChanging(string value);
    partial void OnNGANHDAOTAOChanged();
    partial void OnNOIDAOTAOChanging(string value);
    partial void OnNOIDAOTAOChanged();
    partial void OnHINHTHUCDAOTAOChanging(string value);
    partial void OnHINHTHUCDAOTAOChanged();
    #endregion
		
		public TRINHDOCHUYENMON()
		{
			this._NHANVIIENs = new EntitySet<NHANVIIEN>(new Action<NHANVIIEN>(this.attach_NHANVIIENs), new Action<NHANVIIEN>(this.detach_NHANVIIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TDCHUYENMON", DbType="Char(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_TDCHUYENMON
		{
			get
			{
				return this._ID_TDCHUYENMON;
			}
			set
			{
				if ((this._ID_TDCHUYENMON != value))
				{
					this.OnID_TDCHUYENMONChanging(value);
					this.SendPropertyChanging();
					this._ID_TDCHUYENMON = value;
					this.SendPropertyChanged("ID_TDCHUYENMON");
					this.OnID_TDCHUYENMONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRINHDO_CHUYENMON", DbType="NVarChar(50)")]
		public string TRINHDO_CHUYENMON
		{
			get
			{
				return this._TRINHDO_CHUYENMON;
			}
			set
			{
				if ((this._TRINHDO_CHUYENMON != value))
				{
					this.OnTRINHDO_CHUYENMONChanging(value);
					this.SendPropertyChanging();
					this._TRINHDO_CHUYENMON = value;
					this.SendPropertyChanged("TRINHDO_CHUYENMON");
					this.OnTRINHDO_CHUYENMONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANGCAP", DbType="NVarChar(50)")]
		public string BANGCAP
		{
			get
			{
				return this._BANGCAP;
			}
			set
			{
				if ((this._BANGCAP != value))
				{
					this.OnBANGCAPChanging(value);
					this.SendPropertyChanging();
					this._BANGCAP = value;
					this.SendPropertyChanged("BANGCAP");
					this.OnBANGCAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOCVAN_PHOTHONG", DbType="NVarChar(50)")]
		public string HOCVAN_PHOTHONG
		{
			get
			{
				return this._HOCVAN_PHOTHONG;
			}
			set
			{
				if ((this._HOCVAN_PHOTHONG != value))
				{
					this.OnHOCVAN_PHOTHONGChanging(value);
					this.SendPropertyChanging();
					this._HOCVAN_PHOTHONG = value;
					this.SendPropertyChanged("HOCVAN_PHOTHONG");
					this.OnHOCVAN_PHOTHONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGANHDAOTAO", DbType="NVarChar(50)")]
		public string NGANHDAOTAO
		{
			get
			{
				return this._NGANHDAOTAO;
			}
			set
			{
				if ((this._NGANHDAOTAO != value))
				{
					this.OnNGANHDAOTAOChanging(value);
					this.SendPropertyChanging();
					this._NGANHDAOTAO = value;
					this.SendPropertyChanged("NGANHDAOTAO");
					this.OnNGANHDAOTAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOIDAOTAO", DbType="NVarChar(50)")]
		public string NOIDAOTAO
		{
			get
			{
				return this._NOIDAOTAO;
			}
			set
			{
				if ((this._NOIDAOTAO != value))
				{
					this.OnNOIDAOTAOChanging(value);
					this.SendPropertyChanging();
					this._NOIDAOTAO = value;
					this.SendPropertyChanged("NOIDAOTAO");
					this.OnNOIDAOTAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHTHUCDAOTAO", DbType="NVarChar(50)")]
		public string HINHTHUCDAOTAO
		{
			get
			{
				return this._HINHTHUCDAOTAO;
			}
			set
			{
				if ((this._HINHTHUCDAOTAO != value))
				{
					this.OnHINHTHUCDAOTAOChanging(value);
					this.SendPropertyChanging();
					this._HINHTHUCDAOTAO = value;
					this.SendPropertyChanged("HINHTHUCDAOTAO");
					this.OnHINHTHUCDAOTAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRINHDOCHUYENMON_NHANVIIEN", Storage="_NHANVIIENs", ThisKey="ID_TDCHUYENMON", OtherKey="ID_TDCHUYENMON")]
		public EntitySet<NHANVIIEN> NHANVIIENs
		{
			get
			{
				return this._NHANVIIENs;
			}
			set
			{
				this._NHANVIIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NHANVIIENs(NHANVIIEN entity)
		{
			this.SendPropertyChanging();
			entity.TRINHDOCHUYENMON = this;
		}
		
		private void detach_NHANVIIENs(NHANVIIEN entity)
		{
			this.SendPropertyChanging();
			entity.TRINHDOCHUYENMON = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UNGVIEN")]
	public partial class UNGVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_UNGVIEN;
		
		private string _HoTen;
		
		private string _GioiTinh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _NoiSinh;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private string _Email;
		
		private string _QuocTich;
		
		private string _DanToc;
		
		private string _TonGiao;
		
		private string _HocVan;
		
		private string _NgoaiNgu;
		
		private string _TinHoc;
		
		private string _SoCMND;
		
		private System.Nullable<System.DateTime> _NgayCapCMND;
		
		private string _NoiCapCMND;
		
		private string _TinhTrangSucKhoe;
		
		private System.Nullable<double> _ChieuCao;
		
		private System.Nullable<double> _CanNang;
		
		private string _TrinhDoChuyenMon;
		
		private string _CongViecTungLam;
		
		private string _KinhNghiemLamViec;
		
		private System.Nullable<System.DateTime> _NgayNopHoSo;
		
		private string _CacBangCap;
		
		private string _ViTriUngTuyen;
		
		private System.Nullable<int> _MucLuongMongMuon;
		
		private string _GhiChu;
		
		private System.Nullable<int> _MaDotTuyenDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_UNGVIENChanging(int value);
    partial void OnID_UNGVIENChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnNoiSinhChanging(string value);
    partial void OnNoiSinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnQuocTichChanging(string value);
    partial void OnQuocTichChanged();
    partial void OnDanTocChanging(string value);
    partial void OnDanTocChanged();
    partial void OnTonGiaoChanging(string value);
    partial void OnTonGiaoChanged();
    partial void OnHocVanChanging(string value);
    partial void OnHocVanChanged();
    partial void OnNgoaiNguChanging(string value);
    partial void OnNgoaiNguChanged();
    partial void OnTinHocChanging(string value);
    partial void OnTinHocChanged();
    partial void OnSoCMNDChanging(string value);
    partial void OnSoCMNDChanged();
    partial void OnNgayCapCMNDChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapCMNDChanged();
    partial void OnNoiCapCMNDChanging(string value);
    partial void OnNoiCapCMNDChanged();
    partial void OnTinhTrangSucKhoeChanging(string value);
    partial void OnTinhTrangSucKhoeChanged();
    partial void OnChieuCaoChanging(System.Nullable<double> value);
    partial void OnChieuCaoChanged();
    partial void OnCanNangChanging(System.Nullable<double> value);
    partial void OnCanNangChanged();
    partial void OnTrinhDoChuyenMonChanging(string value);
    partial void OnTrinhDoChuyenMonChanged();
    partial void OnCongViecTungLamChanging(string value);
    partial void OnCongViecTungLamChanged();
    partial void OnKinhNghiemLamViecChanging(string value);
    partial void OnKinhNghiemLamViecChanged();
    partial void OnNgayNopHoSoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayNopHoSoChanged();
    partial void OnCacBangCapChanging(string value);
    partial void OnCacBangCapChanged();
    partial void OnViTriUngTuyenChanging(string value);
    partial void OnViTriUngTuyenChanged();
    partial void OnMucLuongMongMuonChanging(System.Nullable<int> value);
    partial void OnMucLuongMongMuonChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnMaDotTuyenDungChanging(System.Nullable<int> value);
    partial void OnMaDotTuyenDungChanged();
    #endregion
		
		public UNGVIEN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_UNGVIEN", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_UNGVIEN
		{
			get
			{
				return this._ID_UNGVIEN;
			}
			set
			{
				if ((this._ID_UNGVIEN != value))
				{
					this.OnID_UNGVIENChanging(value);
					this.SendPropertyChanging();
					this._ID_UNGVIEN = value;
					this.SendPropertyChanged("ID_UNGVIEN");
					this.OnID_UNGVIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(5)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiSinh", DbType="NVarChar(30)")]
		public string NoiSinh
		{
			get
			{
				return this._NoiSinh;
			}
			set
			{
				if ((this._NoiSinh != value))
				{
					this.OnNoiSinhChanging(value);
					this.SendPropertyChanging();
					this._NoiSinh = value;
					this.SendPropertyChanged("NoiSinh");
					this.OnNoiSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuocTich", DbType="NVarChar(30)")]
		public string QuocTich
		{
			get
			{
				return this._QuocTich;
			}
			set
			{
				if ((this._QuocTich != value))
				{
					this.OnQuocTichChanging(value);
					this.SendPropertyChanging();
					this._QuocTich = value;
					this.SendPropertyChanged("QuocTich");
					this.OnQuocTichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanToc", DbType="NVarChar(30)")]
		public string DanToc
		{
			get
			{
				return this._DanToc;
			}
			set
			{
				if ((this._DanToc != value))
				{
					this.OnDanTocChanging(value);
					this.SendPropertyChanging();
					this._DanToc = value;
					this.SendPropertyChanged("DanToc");
					this.OnDanTocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TonGiao", DbType="NVarChar(30)")]
		public string TonGiao
		{
			get
			{
				return this._TonGiao;
			}
			set
			{
				if ((this._TonGiao != value))
				{
					this.OnTonGiaoChanging(value);
					this.SendPropertyChanging();
					this._TonGiao = value;
					this.SendPropertyChanged("TonGiao");
					this.OnTonGiaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HocVan", DbType="NVarChar(30)")]
		public string HocVan
		{
			get
			{
				return this._HocVan;
			}
			set
			{
				if ((this._HocVan != value))
				{
					this.OnHocVanChanging(value);
					this.SendPropertyChanging();
					this._HocVan = value;
					this.SendPropertyChanged("HocVan");
					this.OnHocVanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgoaiNgu", DbType="NVarChar(80)")]
		public string NgoaiNgu
		{
			get
			{
				return this._NgoaiNgu;
			}
			set
			{
				if ((this._NgoaiNgu != value))
				{
					this.OnNgoaiNguChanging(value);
					this.SendPropertyChanging();
					this._NgoaiNgu = value;
					this.SendPropertyChanged("NgoaiNgu");
					this.OnNgoaiNguChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinHoc", DbType="NVarChar(30)")]
		public string TinHoc
		{
			get
			{
				return this._TinHoc;
			}
			set
			{
				if ((this._TinHoc != value))
				{
					this.OnTinHocChanging(value);
					this.SendPropertyChanging();
					this._TinHoc = value;
					this.SendPropertyChanged("TinHoc");
					this.OnTinHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoCMND", DbType="VarChar(10)")]
		public string SoCMND
		{
			get
			{
				return this._SoCMND;
			}
			set
			{
				if ((this._SoCMND != value))
				{
					this.OnSoCMNDChanging(value);
					this.SendPropertyChanging();
					this._SoCMND = value;
					this.SendPropertyChanged("SoCMND");
					this.OnSoCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapCMND", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayCapCMND
		{
			get
			{
				return this._NgayCapCMND;
			}
			set
			{
				if ((this._NgayCapCMND != value))
				{
					this.OnNgayCapCMNDChanging(value);
					this.SendPropertyChanging();
					this._NgayCapCMND = value;
					this.SendPropertyChanged("NgayCapCMND");
					this.OnNgayCapCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiCapCMND", DbType="NVarChar(50)")]
		public string NoiCapCMND
		{
			get
			{
				return this._NoiCapCMND;
			}
			set
			{
				if ((this._NoiCapCMND != value))
				{
					this.OnNoiCapCMNDChanging(value);
					this.SendPropertyChanging();
					this._NoiCapCMND = value;
					this.SendPropertyChanged("NoiCapCMND");
					this.OnNoiCapCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrangSucKhoe", DbType="NVarChar(50)")]
		public string TinhTrangSucKhoe
		{
			get
			{
				return this._TinhTrangSucKhoe;
			}
			set
			{
				if ((this._TinhTrangSucKhoe != value))
				{
					this.OnTinhTrangSucKhoeChanging(value);
					this.SendPropertyChanging();
					this._TinhTrangSucKhoe = value;
					this.SendPropertyChanged("TinhTrangSucKhoe");
					this.OnTinhTrangSucKhoeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChieuCao", DbType="Float")]
		public System.Nullable<double> ChieuCao
		{
			get
			{
				return this._ChieuCao;
			}
			set
			{
				if ((this._ChieuCao != value))
				{
					this.OnChieuCaoChanging(value);
					this.SendPropertyChanging();
					this._ChieuCao = value;
					this.SendPropertyChanged("ChieuCao");
					this.OnChieuCaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanNang", DbType="Float")]
		public System.Nullable<double> CanNang
		{
			get
			{
				return this._CanNang;
			}
			set
			{
				if ((this._CanNang != value))
				{
					this.OnCanNangChanging(value);
					this.SendPropertyChanging();
					this._CanNang = value;
					this.SendPropertyChanged("CanNang");
					this.OnCanNangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrinhDoChuyenMon", DbType="NVarChar(50)")]
		public string TrinhDoChuyenMon
		{
			get
			{
				return this._TrinhDoChuyenMon;
			}
			set
			{
				if ((this._TrinhDoChuyenMon != value))
				{
					this.OnTrinhDoChuyenMonChanging(value);
					this.SendPropertyChanging();
					this._TrinhDoChuyenMon = value;
					this.SendPropertyChanged("TrinhDoChuyenMon");
					this.OnTrinhDoChuyenMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CongViecTungLam", DbType="NVarChar(50)")]
		public string CongViecTungLam
		{
			get
			{
				return this._CongViecTungLam;
			}
			set
			{
				if ((this._CongViecTungLam != value))
				{
					this.OnCongViecTungLamChanging(value);
					this.SendPropertyChanging();
					this._CongViecTungLam = value;
					this.SendPropertyChanged("CongViecTungLam");
					this.OnCongViecTungLamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KinhNghiemLamViec", DbType="NVarChar(100)")]
		public string KinhNghiemLamViec
		{
			get
			{
				return this._KinhNghiemLamViec;
			}
			set
			{
				if ((this._KinhNghiemLamViec != value))
				{
					this.OnKinhNghiemLamViecChanging(value);
					this.SendPropertyChanging();
					this._KinhNghiemLamViec = value;
					this.SendPropertyChanged("KinhNghiemLamViec");
					this.OnKinhNghiemLamViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNopHoSo", DbType="Date")]
		public System.Nullable<System.DateTime> NgayNopHoSo
		{
			get
			{
				return this._NgayNopHoSo;
			}
			set
			{
				if ((this._NgayNopHoSo != value))
				{
					this.OnNgayNopHoSoChanging(value);
					this.SendPropertyChanging();
					this._NgayNopHoSo = value;
					this.SendPropertyChanged("NgayNopHoSo");
					this.OnNgayNopHoSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CacBangCap", DbType="NVarChar(50)")]
		public string CacBangCap
		{
			get
			{
				return this._CacBangCap;
			}
			set
			{
				if ((this._CacBangCap != value))
				{
					this.OnCacBangCapChanging(value);
					this.SendPropertyChanging();
					this._CacBangCap = value;
					this.SendPropertyChanged("CacBangCap");
					this.OnCacBangCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViTriUngTuyen", DbType="NVarChar(50)")]
		public string ViTriUngTuyen
		{
			get
			{
				return this._ViTriUngTuyen;
			}
			set
			{
				if ((this._ViTriUngTuyen != value))
				{
					this.OnViTriUngTuyenChanging(value);
					this.SendPropertyChanging();
					this._ViTriUngTuyen = value;
					this.SendPropertyChanged("ViTriUngTuyen");
					this.OnViTriUngTuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MucLuongMongMuon", DbType="Int")]
		public System.Nullable<int> MucLuongMongMuon
		{
			get
			{
				return this._MucLuongMongMuon;
			}
			set
			{
				if ((this._MucLuongMongMuon != value))
				{
					this.OnMucLuongMongMuonChanging(value);
					this.SendPropertyChanging();
					this._MucLuongMongMuon = value;
					this.SendPropertyChanged("MucLuongMongMuon");
					this.OnMucLuongMongMuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(100)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDotTuyenDung", DbType="Int")]
		public System.Nullable<int> MaDotTuyenDung
		{
			get
			{
				return this._MaDotTuyenDung;
			}
			set
			{
				if ((this._MaDotTuyenDung != value))
				{
					this.OnMaDotTuyenDungChanging(value);
					this.SendPropertyChanging();
					this._MaDotTuyenDung = value;
					this.SendPropertyChanged("MaDotTuyenDung");
					this.OnMaDotTuyenDungChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
